### PR TITLE
idea for mark_changed api improvement

### LINKED ISSUE #46: `mark_changed` needs better docs, perhaps a better API
After several hours of debugging, I finally solved a SqlAlchemy issue:

1. `mark_changed` has an undocumented `keep_session` kwarg, which defaults to `False`
2. `mark_changed` is unaware of how the session was registered (i.e. what the user intended `keep_session` to be)

My first suggestion is to update the docs/readme to point this out.  

My second suggestion is to extend the `ZopeTransactionEvents` object to have it's own `join_transaction` and `mark_changed` functions, which invoke the global ones with the configured `keep_session` or anything else.

Since `register` returns the configured extension, this would allow a developer to invoke `ext.mark_changed(dbSession)` and preserve the value of `keep_session`.  I'd be happy to generate a PR for this.

### PR DESCRIPTION
**Pull request by jvanasco**
fixes #46 

it doesn't include tests.  the `register(` system doesn't seem to have tests, so I didn't have anything to base it off of.

### CODE REVIEW

**Comment by jugmac00** [comment]
I am by no means qualified to review this PR, but it would certainly help if the PR passes the test suite.

**Comment by icemac** [comment]
Is there any interest to complete this PR or should it get closed without merging?

**Comment by jvanasco** [comment]
Sorry, I had no idea it failed the test suite. My python didn't pick up the tests that run through the sample code in the documentation, and Github doesn't show tests on all screens. 

I'll address this now. I am willing to work on this PR to handle any changes necessary.

**Review by icemac — APPROVED** [review]
The changes look reasonable to me.

The policies of the Zopefoundation organization say what code changes can only be merged with a  signed contributor agreement.
See https://www.zope.org/developer/becoming-a-committer.html for the document.
After submitting it you become a contributor in the zopefoundation organization and are able to merge the PR yourself. (Merging PRs by the creator is part of the policy to prove that you have signed the contributor agreement.)

**Comment by jvanasco** [comment]
@icemac Thanks. I'll get to that this weekend. I thought I had an agreement with Zope via other projects/commits, but it looks like I may have been contributed to forks instead.

**Comment by jvanasco** [comment]
Unfortunately, I am not allowed to sign the Zope Contributor Agreement due to the specific wording of a clause that deals with IP rights.

I emailed with the Zope Foundation about alternatives, asking if there was an alternate agreement without a specific line or if I could provide the PR under a different method.

They suggested I offer the patch/PR under a BSD compatible license.  I can do that, but I can also offer this PR under the existing ZPL license (which should require no action by me) or dedicate it to the public domain. I think there was some confusion on the legal issue I raised with them - the license is fine, it's only the contributor agreement that I am not allowed to sign.

**Comment by icemac** [comment]
Hi @jvanasco, it seems the only thing to do is to declare the license under which you put your change. I think it should be enough make a statement here in the PR. ZPL would probably the easiest variant to handle.

**Comment by jvanasco** [comment]
@icemac I explicitly submit the contributions in this PR under the existing ZPL License.

**Comment by jvanasco** [comment]
and for posterity, here is a snapshot of this page with my declaration: https://web.archive.org/web/20201124182631/https://github.com/zopefoundation/zope.sqlalchemy/pull/47

**Comment by icemac** [comment]
@jvanasco Thank you. I just added a change log entry to make the PR prefect before merging it.

**Comment by jvanasco** [comment]
Thank you so much for handling this! I’m sorry I could not do it myself.

**Pull request merged**
