### PR TITLE
Drop support for Python 3.3.

### PR DESCRIPTION
**Pull request by icemac**
Additionally clean up Python 3.2 remainders.

### CODE REVIEW

**Comment by icemac** [comment]
@mgedmin Could you please give me rights for PyPI (`icemac`) or cut a release by yourself?

**Comment by mgedmin** [comment]
You have PyPI rights now!

**Comment by icemac** [comment]
@mgedmin Thank you. I created a release: https://pypi.org/project/zope.sqlalchemy/1.0/

**Comment by robertknight** [comment]
Thank-you @icemac 🙏

**Pull request merged**
